wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1671039122.072446
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      2:
      - 1
      - 5
      - 41
      - 49
      - 53
      - 55
      - 63
      - 80
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.7
      5: 0.13.6
      8:
      - 1
      - 3
      - 5
amsgrad:
  desc: null
  value: true
aug_prob:
  desc: null
  value: 0.5
batch_size_train:
  desc: null
  value: 64
batch_size_val:
  desc: null
  value: 128
debug:
  desc: null
  value: false
epochs:
  desc: null
  value: 10
experiment_name:
  desc: null
  value: same valset distribution as testset
focal_loss:
  desc: null
  value: false
image_paths:
  desc: null
  value:
  - dataset (A1) - single nails
  - dataset (A2) - single nails
  - dataset B1
  - dataset B2
  - dataset C
  - dataset D
  - Virtual E Dataset
image_size:
  desc: null
  value: 256
lr:
  desc: null
  value: 0.0005
metrics_avg:
  desc: null
  value: macro
min_lr:
  desc: null
  value: 1.0e-06
mixup:
  desc: null
  value: true
mixup_alpha:
  desc: null
  value: 5
mixup_beta:
  desc: null
  value: 5
model_name:
  desc: null
  value: resnet152
n_fold:
  desc: null
  value: 5
num_classes:
  desc: null
  value: 6
num_workers:
  desc: null
  value: 0
optimizer:
  desc: null
  value: Adam
output_path:
  desc: null
  value: C:\Users\hanne\nail-disease-classification\classification/outputs
oversampling:
  desc: null
  value: false
scheduler:
  desc: null
  value: cosine
seed:
  desc: null
  value: 0
train_with_e_dataset:
  desc: null
  value: true
trn_fold:
  desc: null
  value:
  - 0
use_folds:
  desc: null
  value: true
wandb:
  desc: null
  value: true
warm_up:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 1.0e-06
weighted_loss:
  desc: null
  value: false
